zone_name: "staging.platform.hmcts.net"

ns: []

mx: []

srv: []

A:
  - name: "tax-tribunals"
    ttl: 300
    record:
      - 52.151.100.245
  - name: "tax-tribunals-downloader"
    ttl: 300
    record:
      - 52.151.100.245
  - name: "sds-mtls-api-mgmt-appgw"
    ttl: 300
    record:
      - "20.108.148.125"
  - name: "sds-api-mgmt-appgw"
    ttl: 300
    record:
      - "20.108.148.125"

txt:
  - name: "asuid.help-with-fees"
    ttl: 3600
    record:
      - "ABF985515CE7017CB81683BA683A172F83116EB29083812B5D1C3ED49F13C50D"
  - name: "asuid.staff.help-with-fees"
    ttl: 3600
    record:
      - "ABF985515CE7017CB81683BA683A172F83116EB29083812B5D1C3ED49F13C50D"

cname:
  - name: "afdverify.c100-application"
    ttl: 300
    record: "afdverify.sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
  - name: "c100-application"
    ttl: 300
    record: "sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
  - name: "afdverify.hmi-apim"
    ttl: 3600
    record: "afdverify.hmcts-aat-dbdveha6dnc7ejdt.z01.azurefd.net"
  - name: "hmi-apim"
    ttl: 3600
    record: "hmcts-aat-dbdveha6dnc7ejdt.z01.azurefd.net"
  - name: "_a7c390b60c8a53c3d0bc0ed7f0b93d43"
    ttl: 300
    record: "8A49378F10CA1DB2BDFB0BC43E68D2EF.4119A1D9C9464645E90F4FCE3A4610AA.6fb41c898918ad5a0df0.comodoca.com."
  - name: "toffee"
    ttl: 300
    record: "sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
    shutter: false
  - name: "afdverify.toffee"
    ttl: 3600
    record: "afdverify.sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
  - name: "afdverify.pip"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: "afdverify.vh"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: staff.pip-frontend
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: sign-in.pip-frontend
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: pip-frontend
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: "afdverify.pip-frontend"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: vh-video-web
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-video-web"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: vh-admin-web
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-admin-web"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: vh-test-web
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-test-web"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: sds-api-mgmt
    record: sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net
    ttl: 300
  - name: "afdverify.sds-api-mgmt"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: "signalr"
    ttl: 300
    record: "vh-infra-core-stg.service.signalr.net"
  - name: vh-wowza
    ttl: 300
    record: vh-infra-wowza-stg.uksouth.cloudapp.azure.com
  - name: "pre-portal"
    ttl: 300
    record: "sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
    shutter: false
  - name: "afdverify.pre-portal"
    ttl: 3600
    record: "afdverify.sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
  - name: "staff.help-with-fees"
    ttl: 3600
    record: "hwf-staff-ext-stg.niceglacier-a3f52750.uksouth.azurecontainerapps.io"
  - name: "opal-frontend"
    ttl: 300
    record: "sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
    shutter: false
  - name: "opal-frontend-test"
    ttl: 300
    record: "sdshmcts-stg-abfwhrf8g0btcqhe.z01.azurefd.net"
    shutter: false