ns: []

mx: []

A:
  - name: "tax-tribunals"
    ttl: 300
    record:
      - 52.151.100.245
  - name: "tax-tribunals-downloader"
    ttl: 300
    record:
      - 52.151.100.245
      
txt: []

srv: []

cname:
  - name: "afdverify.c100-application"
    ttl: 300
    record: "afdverify.sdshmcts-stg.azurefd.net"
  - name: "c100-application"
    ttl: 300
    record: "sdshmcts-stg.azurefd.net"
  - name: "afdverify.hmi-apim"
    ttl: 3600
    record: "afdverify.hmcts-aat.azurefd.net"
  - name: "hmi-apim"
    ttl: 3600
    record: "hmcts-aat.azurefd.net"
  - name: "_a7c390b60c8a53c3d0bc0ed7f0b93d43"
    ttl: 300
    record: "8A49378F10CA1DB2BDFB0BC43E68D2EF.4119A1D9C9464645E90F4FCE3A4610AA.6fb41c898918ad5a0df0.comodoca.com."
  - name: "toffee"
    ttl: 300
    record: "sdshmcts-stg.azurefd.net"
    shutter: false
  - name: "afdverify.toffee"
    ttl: 3600
    record: "afdverify.sdshmcts-stg.azurefd.net"
  - name: "afdverify.pip"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: "afdverify.vh"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: staff.pip-frontend
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: sign-in.pip-frontend
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: pip-frontend
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: "afdverify.pip-frontend"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: vh-video-web
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: "afdverify.vh-video-web"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: vh-admin-web
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: "afdverify.vh-admin-web"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: vh-test-web
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: "afdverify.vh-test-web"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: sds-api-mgmt
    record: sdshmcts-stg.azurefd.net
    ttl: 300
  - name: "afdverify.sds-api-mgmt"
    ttl: 300
    record: "afdverify.hmcts-stg.azurefd.net"
  - name: "signalr"
    ttl: 300
    record: "vh-infra-core-stg.service.signalr.net"
  - name: vh-wowza
    ttl: 300
    record: vh-infra-wowza-stg.uksouth.cloudapp.azure.com