ns: []

mx: []

A: []

txt: []

srv: []

cname:
  - name: "afdverify.hmi-apim"
    ttl: 3600
    record: "afdverify.hmcts-aat.azurefd.net"
  - name: "hmi-apim"
    ttl: 3600
    record: "hmcts-aat.azurefd.net"
  - name: "_a7c390b60c8a53c3d0bc0ed7f0b93d43"
    ttl: 300
    record: "8A49378F10CA1DB2BDFB0BC43E68D2EF.4119A1D9C9464645E90F4FCE3A4610AA.6fb41c898918ad5a0df0.comodoca.com."
  - name: “toffee”
    ttl: 300
    record: "sdshmcts-staging.azurefd.net"
    shutter: false
  - name: "afdverify.toffee"
    ttl: 3600
    record: "afdverify.sdshmcts-staging.azurefd.net"

