# Shuttering all A record types requires either of the following values to be set.
# If you shutter all A records via the `shutter_all_a` setting and one of the records does not contain either of these values Terraform will fail.
# - shutter_resource_id
# - alias_target_resource_id
shutter_all_a: false

shutter_all_cname: false

# Shuttering any A record type requires either of the following values to be set.
# If you shutter an A record and one of the records does not contain either of these values Terraform will fail.
# - shutter_resource_id
# - alias_target_resource_id
A: []


cname:
  - name: "_A3AC75C13814E5B2EF9F4BDEDDB85F97.data-analytics"
    shutter: false