# Please be careful with this setting, it will shutter ALL records in this DNS zone
# Please ensure you read all comments first before enabling this option, there are specific requirements
# for A records you must be aware of!
shutter_all: false

# Shuttering all A record types requires either of the following values to be set.
# If you shutter all A records via the `shutter_all_a` setting and one of the records does not contain either of these values Terraform will fail.
# - shutter_resource_id
# - alias_target_resource_id
shutter_all_a: false

shutter_all_cname: false

# Shuttering any A record type requires either of the following values to be set.
# If you shutter an A record and one of the records does not contain either of these values Terraform will fail.
# - shutter_resource_id
# - alias_target_resource_id
A: []

cname:
  - name: "_959babd6a885261723d801a16c89a7b1.vh-notification-api"
    shutter: false
  - name: "_5c7ef33bcb57182a54f2d9cc8d8ac0f8.vh-bookings-api"
    shutter: false
  - name: "_ac285a78514b19d657b18c29b98f4c7f.vh-admin-web"
    shutter: false
  - name: "_df529a77950081e3ad8c21586162089b.vh-video-web"
    shutter: false
  - name: "_0be35efd23b00eb9f75301c49805b99a.vh-user-api"
    shutter: false
  - name: "_9E3AAF42E6ADCEC8607BA5CF5F65A95F.vh-admin-web"
    shutter: false
  - name: "_9E3AAF42E6ADCEC8607BA5CF5F65A95F.admin"
    shutter: false
  - name: "_D7BC9C94CCECEF2B47A23F6CDB45C9A0.vh-user-api"
    shutter: false
