ns: []

mx: []

A:
  - name: "mailrelay"
    ttl: 60
    record:
      - "20.49.168.141"
      - "20.49.168.17"
      - "51.11.124.149"
      - "51.11.124.158"

txt:
  - name: "mailrelay"
    ttl: 3600
    record:
      - "v=spf1 ip4:20.49.168.141 ip4:20.49.168.17 ip4:51.11.124.149 ip4:51.11.124.158 include:spf.protection.outlook.com ~all"
  - name: "_dmarc.mailrelay"
    ttl: 3600
    record:
      - "v=DMARC1; p=none"


srv: []


cname:
  - name: "afdverify.hmi-apim"
    ttl: 3000
    record: "afdverify.hmcts-preview.azurefd.net"
  - name: "hmi-apim"
    ttl: 3000
    record: "hmcts-preview.azurefd.net"
  - name: "toffee"
    ttl: 300
    record: "sdshmcts-dev.azurefd.net"
    shutter: false
  - name: "afdverify.toffee"
    ttl: 3600
    record: "afdverify.sdshmcts-dev.azurefd.net"
  - name: "jdbureau"
    ttl: 300
    record: "sdshmcts-dev.azurefd.net"
    shutter: false
  - name: "afdverify.jdbureau"
    ttl: 3600
    record: "afdverify.sdshmcts-dev.azurefd.net"
  - name: "jdfrontend"
    ttl: 300
    record: "sdshmcts-dev.azurefd.net"
    shutter: false
  - name: "afdverify.jdfrontend"
    ttl: 3600
    record: "afdverify.sdshmcts-dev.azurefd.net"
  - name: vh-video-web
    record: sdshmcts-dev.azurefd.net
    ttl: 300
  - name: "afdverify.vh-video-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: vh-admin-web
    record: sdshmcts-dev.azurefd.net
    ttl: 300
  - name: "afdverify.vh-admin-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: vh-service-web
    record: sdshmcts-dev.azurefd.net
    ttl: 300
  - name: "afdverify.vh-service-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: vh-test-web
    record: sdshmcts-dev.azurefd.net
    ttl: 300
  - name: "afdverify.vh-test-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: sds-api-mgmt
    record: sdshmcts-dev.azurefd.net
    ttl: 300
  - name: "afdverify.sds-api-mgmt"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
