ns: []

mx: []

A: []

txt: []

srv: []


cname:
  - name: "afdverify.hmi-apim"
    ttl: 3000
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: "hmi-apim"
    ttl: 3000
    record: "hmcts-dev.azurefd.net"
