zone_name: "dev.platform.hmcts.net"

ns: []

mx: []

srv: []

A:
  - name: "mailrelay"
    ttl: 60
    record:
      - "20.49.168.141"
      - "20.49.168.17"
      - "51.11.124.149"
      - "51.11.124.158"

  - name: "sds-mtls-api-mgmt-appgw"
    ttl: 60
    record:
      - "20.254.22.0"

  - name: "sds-api-mgmt-appgw"
    ttl: 60
    record:
      - "20.254.22.0"

txt:
  - name: "mailrelay"
    ttl: 3600
    record:
      - "v=spf1 ip4:20.49.168.141 ip4:20.49.168.17 ip4:51.11.124.149 ip4:51.11.124.158 include:spf.protection.outlook.com ~all"
  - name: "_dmarc.mailrelay"
    ttl: 3600
    record:
      - "v=DMARC1; p=none"
  - name: "@"
    ttl: 3600
    record:
      - "MS=ms74851057"
  - name: "asuid.help-with-fees"
    ttl: 3600
    record:
      - "ABF985515CE7017CB81683BA683A172F83116EB29083812B5D1C3ED49F13C50D"
  - name: "asuid.staff.help-with-fees"
    ttl: 3600
    record:
      - "ABF985515CE7017CB81683BA683A172F83116EB29083812B5D1C3ED49F13C50D"
  - name: "asuid.wsproxy"
    ttl: 3600
    record:
      - "ABF985515CE7017CB81683BA683A172F83116EB29083812B5D1C3ED49F13C50D"

cname:
  - name: "afdverify.hmi-apim"
    ttl: 3000
    record: "afdverify.hmcts-preview-fkhfehdgahcrhbds.z01.azurefd.net"
  - name: "hmi-apim"
    ttl: 3000
    record: "hmcts-preview-fkhfehdgahcrhbds.z01.azurefd.net"
  - name: "toffee"
    ttl: 300
    record: "sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
    shutter: false
  - name: "afdverify.toffee"
    ttl: 3600
    record: "afdverify.sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
  - name: "jdbureau"
    ttl: 300
    record: "sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
    shutter: false
  - name: "afdverify.jdbureau"
    ttl: 3600
    record: "afdverify.sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
  - name: "jdfrontend"
    ttl: 300
    record: "sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
    shutter: false
  - name: "afdverify.jdfrontend"
    ttl: 3600
    record: "afdverify.sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
  - name: sds-api-mgmt
    record: sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net
    ttl: 300
  - name: "afdverify.sds-api-mgmt"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: vh-video-web
    record: sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-video-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: vh-admin-web
    record: sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-admin-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: vh-test-web
    record: sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-test-web"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: "signalr"
    ttl: 300
    record: "vh-infra-core-dev.service.signalr.net"
  - name: "vh-wowza"
    ttl: 300
    record: "vh-infra-wowza-dev.uksouth.cloudapp.azure.com"
  - name: vh-video-web-pr-2142
    record: sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net
    ttl: 300
  - name: "afdverify.vh-video-web-pr-2142"
    ttl: 300
    record: "afdverify.hmcts-dev.azurefd.net"
  - name: "pre-portal"
    ttl: 300
    record: "sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
    shutter: false
  - name: "afdverify.pre-portal"
    ttl: 3600
    record: "afdverify.sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
  - name: "opal-frontend"
    ttl: 300
    record: "sdshmcts-dev-c4ercybwaubzbmfn.z01.azurefd.net"
