ns: []

mx: []

A: []

txt: []

srv: []


cname:
  - name: "afdverify.hmi-apim"
    ttl: 3000
    record: "afdverify.hmcts-preview.azurefd.net"
  - name: "hmi-apim"
    ttl: 3000
    record: "hmcts-preview.azurefd.net"
  - name: “toffee”
    ttl: 300
    record: "sdshmcts-dev.azurefd.net"
    shutter: false
  - name: "afdverify.toffee"
    ttl: 3600
    record: "afdverify.sdshmcts-dev.azurefd.net"

